*Start modifying en.js
Server-Analytics/languages pull request #10
Opened 2022-02-24 20:59 UTC by Bouse2Vache

2022-02-24 21:06 UTC, UBrainDev requested changes
C'est top ! Merci beaucoup. J'ai relevé deux/trois entrées qui semblent incorrectes en y ajoutant des commentaires correspondant :)
Une fois fixé, la PR sera prête à être pushée !

2022-02-24 21:06 UTC, UBrainDev commented on en.js
> +            description: "Thanks for using **{projectName}** v.Me**{version}** ! *You can consult the last patch note by clicking [**here**]({lastPatchNoteLink}).*",
Je pense qu'il y a un "Me" en trop avant `**{version}**`

2022-02-24 21:06 UTC, UBrainDev commented on en.js
> +                STATS: "Statistical commands",
"Insights" ne serait pas mieux ? La phrase à une tournure étrange (dans mon opinion).

2022-02-24 21:06 UTC, UBrainDev commented on en.js
> +                short_description: "Generate a graph"
"Chart" est plus correct en Anglais, je crois

2022-02-24 21:07 UTC, Bouse2Vache commented on en.js
> +            description: "Thanks for using **{projectName}** v.Me**{version}** ! *You can consult the last patch note by clicking [**here**]({lastPatchNoteLink}).*",
Oui désolé, c’est le correcteur automatique de mon ipad 😓
Je ferais les corrections sur mon ordi ce week-end, ce sera plus simple 😎

2022-02-24 21:08 UTC, Bouse2Vache commented on en.js
> +                STATS: "Statistical commands",
Ok, je modifie !

2022-02-24 21:08 UTC, Bouse2Vache commented on en.js
> +                short_description: "Generate a graph"
Ok, au temps pour moi… je modifie !

2022-02-24 21:11 UTC, Bouse2Vache commented on en.js
> +                STATS: "Statistical commands",
Euh… ce serait plus **Statistical insights** ou **Insights commands** ahaha 
J’ai un doute 😰

2022-02-24 21:14 UTC, Bouse2Vache commented
> C'est top ! Merci beaucoup. J'ai relevé deux/trois entrées qui semblent incorrectes en y ajoutant des commentaires correspondant :)
> Une fois fixé, la PR sera prête à être pushée !

On ne va pas push pour juste ça non ? XD
@UBrainDev, à part si tu fais les updates en 2 secondes 👀

2022-02-24 21:17 UTC, UBrainDev commented on en.js
> +                STATS: "Statistical commands",
Je pensais plutôt tout simplement à "Insights", sans plus

2022-02-25 15:29 UTC, UBrainDev commented
Je me suis appuyé de tes traductions en les entremêlants avec celles de @leshiirudo, en conséquent je close cette pull request vu qu'elle n'est plus compatible avec la nouvelle structure du repo, mais dans tous les cas; merci !

2022-02-25 15:29 UTC, closed without merging